### ISSUE TITLE
sfml-audio dylib built from source depends on Vorbisenc

### ISSUE THREAD

**Issue by NQNStudios** [oprypin/install-sfml#2]
This might be a problem with my build, if I figure it out I will close this. If not, I'll edit with as much info as I can

**Comment by oprypin** [comment]
I could be doing things totally wrong and still have no clue how to do them right 🥲
Mac support was always just barely working because it keeps changing and I don't use Mac myself

**Comment by NQNStudios** [comment]
You’re not! It works.
